ALTER TABLE words 
ADD COLUMN IF NOT EXISTS formality INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS culturalsensitivity INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS figurativeness INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS complexity INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS political INT DEFAULT 0;
