name: Apply Migrations
on:
    workflow_dispatch: # manual triggers

jobs:
    migrate:
        runs-on: ubuntu-latest
        environment: staging
        env:
            DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install CockroachDB Client
              run: |
                curl https://binaries.cockroachdb.com/cockroach-latest.linux-amd64.tgz | tar xvz
                sudo mv cockroach-latest.linux-amd64/cockroach /usr/local/bin/

            - name: Apply SQL
              run: |
                for file in $(ls Scripts/*.sql | sort); do
                  echo "Applying $file..."
                  cockroach sql --url="$DB_CONNECTION_STRING" --file="$file"
                done