name: Build and Deploy

on:
    push:
        branches:
          - main
        
        tags:
          - 'v*'
    
    pull_request:
        branches:
            - main
    
    workflow_dispatch: # manual triggers

jobs:
    build:
        runs-on: ubuntu-24.04-arm
        environment: staging
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'

            - name: Setup AOT dependencies
              run: |
                sudo apt-get update && sudo apt-get install -y clang zlib1g-dev

            - name: Restore Dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

    deploy:
        needs: build        
        runs-on: ubuntu-24.04-arm
        permissions:
          contents: write
          issues: write
          pull-requests: write
          id-token: write
          packages: write 
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Extract version
              run: |
                TAG=${GITHUB_REF#refs/tags/v}
                echo "PACKAGE_VERSION=$TAG" >> $GITHUB_ENV

            - name: Update .csproj version
              run: |
                sed -i "s|<Version>.*</Version>|<Version>${PACKAGE_VERSION}</Version>|g" WordList.Common.csproj
                                  
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'

            - name: Setup AOT dependencies
              run: |
                sudo apt-get update && sudo apt-get install -y clang zlib1g-dev

            - name: Restore Dependencies
              run: dotnet restore

            - name: Build & Pack NuGet Package
              run: dotnet pack --configuration Release --no-restore --output ./packages

            - name: Publish NuGet Package
              run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/word-list/index.json"
